[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
anyhow = "1.0.68"
thiserror = "1.0.38"
aoc_lib = { path = "../aoc_lib" }